# Generated by Django 4.0 on 2022-01-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bill', models.CharField(default='', max_length=10)),
                ('fixing_Charge', models.FloatField()),
                ('sparepart_price', models.FloatField()),
                ('total_Charge', models.FloatField()),
                ('DateTime', models.DateTimeField(verbose_name='Date & Time')),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default='', max_length=30)),
                ('type', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('Price_Per_Unit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('account_Number', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='sparepart_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('DateTime', models.DateTimeField(verbose_name='Date & Time')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.supplier')),
            ],
            options={
                'verbose_name': 'Spareparts Order',
                'verbose_name_plural': 'Spareparts Orders',
            },
        ),
        migrations.CreateModel(
            name='import_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('Price_Per_Unit_Imp', models.FloatField()),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sparepart')),
                ('sparepart_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sparepart_order')),
            ],
            options={
                'verbose_name': 'Import Part',
                'verbose_name_plural': 'Import Parts',
            },
        ),
        migrations.CreateModel(
            name='export_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('id_bill', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.bill')),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sparepart')),
            ],
            options={
                'verbose_name': 'Export Part',
                'verbose_name_plural': 'Export Parts',
            },
        ),
        migrations.CreateModel(
            name='customer_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer')),
            ],
            options={
                'verbose_name': 'Customer Car',
                'verbose_name_plural': 'Customer Cars',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_Car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer_car'),
        ),
    ]
