# Generated by Django 4.0 on 2022-01-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id_bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.export_part'),
        ),
        migrations.AlterField(
            model_name='export_part',
            name='id_bill',
            field=models.CharField(default='', max_length=10),
        ),
    ]
