# Generated by Django 4.0 on 2022-01-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_bill_id_bill_remove_export_part_id_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='id_bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.export_bill'),
        ),
        migrations.AlterField(
            model_name='export_bill',
            name='id_bill',
            field=models.CharField(default='', max_length=10),
        ),
    ]
