# Generated by Django 4.0 on 2022-01-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_export_part_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='export_part',
            name='DateTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
