# Generated by Django 4.0 on 2022-01-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_export_part_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_car',
            name='car',
        ),
        migrations.RemoveField(
            model_name='customer_car',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer_car',
            name='license',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer_car',
            name='name',
            field=models.CharField(default='บิลเงินสด', max_length=40),
        ),
        migrations.AddField(
            model_name='customer_car',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
