# Generated by Django 4.0 on 2022-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_customer_car_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_car',
            name='name',
            field=models.CharField(default='บิลเงินสด', max_length=40, null=True),
        ),
    ]
