# Generated by Django 4.0 on 2022-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_customer_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_car',
            name='license',
            field=models.CharField(default='', max_length=10),
        ),
    ]
