# Generated by Django 4.0 on 2022-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_customer_car_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='export_part',
            name='id_bill',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
