# Generated by Django 4.0 on 2022-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_export_bill_part_all_export_bill_part_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_car',
            name='license',
            field=models.CharField(max_length=10),
        ),
    ]
