# Generated by Django 4.0 on 2022-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_customer_car_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_part',
            name='sparepart_order',
        ),
        migrations.AddField(
            model_name='import_part',
            name='id_import',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sparepart_order',
            name='id_import',
            field=models.CharField(default='', max_length=10),
        ),
    ]
