# Generated by Django 4.0 on 2022-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_import_part_sparepart_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_part',
            name='DateTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
