# Generated by Django 4.0 on 2022-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_import_part_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import_part',
            name='Price_Per_Unit_Imp',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='Price_Per_Unit_Imp',
            field=models.FloatField(null=True),
        ),
    ]
