# Generated by Django 4.0 on 2022-04-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_import_part_price_per_unit_imp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='import_wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_import', models.CharField(default='', max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('DateTime', models.DateField(blank=True, null=True)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sparepart')),
            ],
            options={
                'verbose_name': 'Import Wait',
                'verbose_name_plural': 'Import Wait',
            },
        ),
    ]
