# Generated by Django 4.0 on 2022-04-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_import_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_wait',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.supplier'),
        ),
    ]
