# Generated by Django 4.0 on 2022-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_import_wait_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='inventory',
            field=models.CharField(default='', max_length=40),
        ),
    ]
